[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "flask>=3.1.2",
    "python-dotenv>=1.1.1",
    "sendgrid>=6.12.4",
    "werkzeug>=3.1.3",
]
